import { Question } from './types';

// Scoring Rule:
// A -> First letter of dimension (E, S, T, J)
// B -> Second letter of dimension (I, N, F, P)

export const QUESTIONS: Question[] = [
  // --- E vs I (20 Questions) ---
  { id: 1, dimension: 'EI', text: "与人交往后，你更常感觉：", optionA: "精力充沛", optionB: "需要独处恢复" },
  { id: 2, dimension: 'EI', text: "面对新环境，你更倾向于：", optionA: "主动结识他人", optionB: "观察后再融入" },
  { id: 3, dimension: 'EI', text: "分享想法时，你习惯：", optionA: "边说边梳理，越说越清晰", optionB: "先想透，再有条理表达" },
  { id: 4, dimension: 'EI', text: "空闲时间，你更爱：", optionA: "参与聚会、户外活动", optionB: "居家做事、独处放松" },
  { id: 5, dimension: 'EI', text: "团队讨论中，你通常：", optionA: "主动发言，乐于主导话题", optionB: "倾听为主，必要时补充" },
  { id: 6, dimension: 'EI', text: "接到陌生社交邀请，你更可能：", optionA: "欣然接受，愿意尝试", optionB: "委婉拒绝，优先选熟悉场景" },
  { id: 7, dimension: 'EI', text: "压力大时，你缓解情绪的方式更偏向：", optionA: "和亲友倾诉、吐槽", optionB: "自己消化、做喜欢的事" },
  { id: 8, dimension: 'EI', text: "学习新技能，你更喜欢：", optionA: "报线下班，和他人互动学习", optionB: "自学网课，按自己节奏推进" },
  { id: 9, dimension: 'EI', text: "对热闹场合的感受：", optionA: "享受氛围，不觉得累", optionB: "短暂参与可，久待易疲惫" },
  { id: 10, dimension: 'EI', text: "表达需求时，你更习惯：", optionA: "直接说出，不绕弯", optionB: "顾虑他人感受，委婉表达" },
  { id: 11, dimension: 'EI', text: "社交中，你更擅长：", optionA: "快速和陌生人拉近距离", optionB: "深耕少数亲密关系" },
  { id: 12, dimension: 'EI', text: "完成重要事之后，你想做的是：", optionA: "和他人分享成果", optionB: "独自休息、沉淀" },
  { id: 13, dimension: 'EI', text: "面对公开演讲，你更倾向于：", optionA: "主动争取，享受展示", optionB: "尽量回避，迫不得已才参与" },
  { id: 14, dimension: 'EI', text: "日常沟通，你偏爱：", optionA: "面对面聊天、打电话", optionB: "文字消息，可随时回复" },
  { id: 15, dimension: 'EI', text: "参与集体活动后，你第二天状态：", optionA: "依旧饱满", optionB: "需安静独处回血" },
  { id: 16, dimension: 'EI', text: "认识新朋友的动力来自：", optionA: "天生喜欢结识不同的人", optionB: "因共同事/兴趣，被动结识" },
  { id: 17, dimension: 'EI', text: "做决定前，你更想：", optionA: "收集多人意见，综合参考", optionB: "自己先判断，再偶尔咨询信任的人" },
  { id: 18, dimension: 'EI', text: "周末安排，你更常：", optionA: "提前约人，规划社交活动", optionB: "灵活调整，以独处或少数人相处为主" },
  { id: 19, dimension: 'EI', text: "处于人群中，你更易：", optionA: "融入氛围，带动情绪", optionB: "保持距离，专注自身感受" },
  { id: 20, dimension: 'EI', text: "分享喜怒哀乐时，你更倾向于：", optionA: "及时和他人分享", optionB: "自己先接纳，再选择性分享" },

  // --- S vs N (24 Questions) ---
  { id: 21, dimension: 'SN', text: "了解新事物，你更关注：", optionA: "具体细节、实际用途", optionB: "核心逻辑、未来可能性" },
  { id: 22, dimension: 'SN', text: "描述一件事，你更擅长：", optionA: "说清时间、地点、具体过程", optionB: "讲清感受、想法、潜在影响" },
  { id: 23, dimension: 'SN', text: "学习知识，你更习惯：", optionA: "先掌握基础，再逐步深入", optionB: "先抓核心框架，再补细节" },
  { id: 24, dimension: 'SN', text: "买东西时，你优先考虑：", optionA: "材质、价格、实用性", optionB: "设计、理念、独特性" },
  { id: 25, dimension: 'SN', text: "面对问题，你更先关注：", optionA: "当下的具体情况", optionB: "背后的原因、长远影响" },
  { id: 26, dimension: 'SN', text: "记忆信息时，你对以下内容更敏感：", optionA: "具体数据、事实案例", optionB: "抽象概念、关联想法" },
  { id: 27, dimension: 'SN', text: "接受新任务，你更想先知道：", optionA: "具体步骤、明确要求", optionB: "目标方向、可创新空间" },
  { id: 28, dimension: 'SN', text: "观察他人，你更易注意到：", optionA: "穿着、言行等具体表现", optionB: "气质、想法等内在特质" },
  { id: 29, dimension: 'SN', text: "规划未来，你更倾向于：", optionA: "基于过往经验，务实安排", optionB: "畅想多种可能，大胆尝试" },
  { id: 30, dimension: 'SN', text: "学习技能时，你更看重：", optionA: "操作熟练度、实际效果", optionB: "原理理解、灵活应用" },
  { id: 31, dimension: 'SN', text: "看到一篇文章，你更关注：", optionA: "具体内容、实用结论", optionB: "观点逻辑、延伸思考" },
  { id: 32, dimension: 'SN', text: "解决问题，你更依赖：", optionA: "过往经验、已知方法", optionB: "新想法、跨界思路" },
  { id: 33, dimension: 'SN', text: "对“未来”的态度，你更偏向：", optionA: "基于现实，稳步规划", optionB: "保持开放，期待新变化" },
  { id: 34, dimension: 'SN', text: "评价一件作品，你更看重：", optionA: "做工、细节、实用性", optionB: "创意、内涵、独特性" },
  { id: 35, dimension: 'SN', text: "接收信息时，你更易被哪种吸引：", optionA: "具体、真实、可验证的内容", optionB: "抽象、新颖、有想象空间的内容" },
  { id: 36, dimension: 'SN', text: "安排行程，你更习惯：", optionA: "明确时间、地点、路线", optionB: "确定大致方向，灵活调整" },
  { id: 37, dimension: 'SN', text: "面对新领域，你入门方式更偏向：", optionA: "从基础细节学起，循序渐进", optionB: "先了解整体逻辑，再找兴趣点深入" },
  { id: 38, dimension: 'SN', text: "记住一个人的关键，你更靠：", optionA: "外貌、言行等具体特征", optionB: "相处感受、价值观契合度" },
  { id: 39, dimension: 'SN', text: "思考问题时，你更易陷入：", optionA: "具体的细节梳理", optionB: "抽象的关联联想" },
  { id: 40, dimension: 'SN', text: "选择学习内容，你更倾向于：", optionA: "实用型、能直接应用的", optionB: "兴趣型、能拓展认知的" },
  { id: 41, dimension: 'SN', text: "描述计划，你更擅长：", optionA: "说清具体步骤、时间节点", optionB: "讲清目标意义、潜在价值" },
  { id: 42, dimension: 'SN', text: "面对变化，你更关注：", optionA: "变化带来的具体影响", optionB: "变化背后的机会与趋势" },
  { id: 43, dimension: 'SN', text: "观察环境，你更易注意到：", optionA: "环境中的具体物品、细节变化", optionB: "环境的整体氛围、潜在状态" },
  { id: 44, dimension: 'SN', text: "接受建议时，你更认可：", optionA: "有具体案例、可落地的", optionB: "有逻辑支撑、有新思路的" },

  // --- T vs F (22 Questions) ---
  { id: 45, dimension: 'TF', text: "解决冲突，你更优先考虑：", optionA: "对错逻辑、公平公正", optionB: "他人情绪、关系和谐" },
  { id: 46, dimension: 'TF', text: "评价他人，你更看重：", optionA: "能力、效率、责任心", optionB: "善良、共情、待人态度" },
  { id: 47, dimension: 'TF', text: "做重要决定，你更依赖：", optionA: "理性分析、客观数据", optionB: "内心感受、价值观契合" },
  { id: 48, dimension: 'TF', text: "他人犯错时，你更倾向于：", optionA: "直接指出问题，给出改进建议", optionB: "先安抚情绪，再委婉提醒" },
  { id: 49, dimension: 'TF', text: "面对利益取舍，你更习惯：", optionA: "按规则、公平分配", optionB: "优先照顾弱势方、维护关系" },
  { id: 50, dimension: 'TF', text: "工作中，你更认可：", optionA: "结果优先，效率至上", optionB: "过程和谐，团队氛围重要" },
  { id: 51, dimension: 'TF', text: "反驳他人观点时，你会：", optionA: "直接说清逻辑漏洞", optionB: "先肯定部分，再表达不同意见" },
  { id: 52, dimension: 'TF', text: "选择职业，你更看重：", optionA: "发展前景、薪资待遇", optionB: "工作氛围、是否符合内心期待" },
  { id: 53, dimension: 'TF', text: "处理争议，你更擅长：", optionA: "梳理利弊，给出中立方案", optionB: "协调各方情绪，寻求共识" },
  { id: 54, dimension: 'TF', text: "评价一件事的好坏，你更看：", optionA: "客观效果、是否合理", optionB: "对他人的影响、是否暖心" },
  { id: 55, dimension: 'TF', text: "他人向你求助，你会：", optionA: "先判断自己是否有能力、是否合理", optionB: "先共情对方，优先伸出援手" },
  { id: 56, dimension: 'TF', text: "团队合作中，你更在意：", optionA: "任务完成质量、效率", optionB: "成员间的配合、是否融洽" },
  { id: 57, dimension: 'TF', text: "做决定后，你更易纠结：", optionA: "逻辑是否通顺、是否最优", optionB: "是否伤害他人、关系是否受影响" },
  { id: 58, dimension: 'TF', text: "面对不公，你更倾向于：", optionA: "直接指出，维护规则", optionB: "委婉协调，避免冲突升级" },
  { id: 59, dimension: 'TF', text: "给他人提建议，你习惯：", optionA: "客观理性，直击问题核心", optionB: "考虑对方感受，语气温和" },
  { id: 60, dimension: 'TF', text: "工作分配，你更认同：", optionA: "按能力分工，各司其职", optionB: "兼顾每个人的意愿，灵活调整" },
  { id: 61, dimension: 'TF', text: "面对选择，你更易陷入：", optionA: "利弊权衡，找最优解", optionB: "顾虑他人感受，难下决定" },
  { id: 62, dimension: 'TF', text: "评价自己的工作，你更看：", optionA: "结果是否达标、是否高效", optionB: "过程中是否用心、是否受认可" },
  { id: 63, dimension: 'TF', text: "冲突中，你更难接受：", optionA: "逻辑混乱、不讲道理", optionB: "态度强硬、不顾及他人情绪" },
  { id: 64, dimension: 'TF', text: "做重要选择，你会优先放弃：", optionA: "不符合逻辑、收益低的", optionB: "违背内心感受、伤害关系的" },
  { id: 65, dimension: 'TF', text: "他人质疑你的决定，你会：", optionA: "摆事实、讲逻辑，证明合理性", optionB: "解释自己的想法，也倾听对方顾虑" },
  { id: 66, dimension: 'TF', text: "团队有分歧，你更倾向于：", optionA: "按客观标准统一意见", optionB: "寻找各方都能接受的折中方案" },

  // --- J vs P (24 Questions) ---
  { id: 67, dimension: 'JP', text: "日常行程，你更习惯：", optionA: "提前规划，按计划执行", optionB: "灵活调整，随心情安排" },
  { id: 68, dimension: 'JP', text: "完成任务，你更倾向于：", optionA: "尽早做完，避免拖延", optionB: "临近截止日期，集中精力完成" },
  { id: 69, dimension: 'JP', text: "面对不确定的事，你更感觉：", optionA: "焦虑，想尽快确定", optionB: "坦然，享受未知的可能" },
  { id: 70, dimension: 'JP', text: "工作/学习结束后，你更爱：", optionA: "整理好物品、复盘总结", optionB: "立刻放下，先放松再处理后续" },
  { id: 71, dimension: 'JP', text: "制定计划，你更擅长：", optionA: "详细具体，明确时间节点", optionB: "大致方向，留足灵活空间" },
  { id: 72, dimension: 'JP', text: "面对突发变化，你更倾向于：", optionA: "尽快调整计划，恢复有序", optionB: "顺势而为，随机应变" },
  { id: 73, dimension: 'JP', text: "买东西前，你会：", optionA: "明确需求，列好清单再买", optionB: "随缘逛，看到合适的再入手" },
  { id: 74, dimension: 'JP', text: "周末到来前，你更常：", optionA: "提前规划好要做的事", optionB: "等周末到了，再临时决定" },
  { id: 75, dimension: 'JP', text: "任务截止日期前，你的状态：", optionA: "提前完成，后续可修改完善", optionB: "前期铺垫，截止前高效冲刺" },
  { id: 76, dimension: 'JP', text: "对生活环境的要求：", optionA: "整洁有序，物品归位", optionB: "舒适自在，不用刻意整齐" },
  { id: 77, dimension: 'JP', text: "接受新任务，你更想：", optionA: "立刻明确流程，开始推进", optionB: "先了解情况，慢慢摸索节奏" },
  { id: 78, dimension: 'JP', text: "计划被打乱，你的感受：", optionA: "烦躁，想尽快回到正轨", optionB: "无所谓，换种方式也可行" },
  { id: 79, dimension: 'JP', text: "日常做事，你更偏向：", optionA: "有条理，一步一步推进", optionB: "灵活随性，想到哪做到哪" },
  { id: 80, dimension: 'JP', text: "考试/考核前，你复习方式：", optionA: "提前制定复习计划，稳步推进", optionB: "临近考试，集中攻克重点" },
  { id: 81, dimension: 'JP', text: "对未完成的事，你更感觉：", optionA: "惦记，想尽快收尾", optionB: "不着急，有时间再处理" },
  { id: 82, dimension: 'JP', text: "旅行前，你会：", optionA: "订好机票酒店、规划好行程路线", optionB: "只订往返交通，当地随缘游玩" },
  { id: 83, dimension: 'JP', text: "工作中，你更适应：", optionA: "有明确规则、固定流程", optionB: "灵活自由，可自主安排节奏" },
  { id: 84, dimension: 'JP', text: "收到多项任务，你会：", optionA: "先排序，按优先级依次完成", optionB: "先做简单的，再逐步攻克难的" },
  { id: 85, dimension: 'JP', text: "生活中，你更偏爱：", optionA: "规律稳定，少变化", optionB: "新鲜多样，常尝试新事物" },
  { id: 86, dimension: 'JP', text: "完成任务后，你会：", optionA: "立刻总结经验，整理成果", optionB: "完成即可，后续有需要再复盘" },
  { id: 87, dimension: 'JP', text: "面对选择，你更习惯：", optionA: "尽快确定，避免纠结", optionB: "多观望，慢慢筛选最优选项" },
  { id: 88, dimension: 'JP', text: "日常作息，你更倾向于：", optionA: "固定时间睡觉、起床", optionB: "随当天状态，灵活调整作息" },
  { id: 89, dimension: 'JP', text: "处理琐事，你会：", optionA: "及时做完，不堆积", optionB: "攒到一起，集中处理" },
  { id: 90, dimension: 'JP', text: "对“完美”的态度，你更偏向：", optionA: "尽量做到极致，不留遗憾", optionB: "完成比完美重要，灵活取舍" },
];
